version: '3'
services:
  server:
    build: .
    environment:
      - VIRTUAL_HOST=static.suilabs.com
      - LETSENCRYPT_HOST=static.suilabs.com
      - LETSENCRYPT_EMAIL=borja.arias.upc@gmail.com
    ports:
      - "3001:3000"
    volumes:
      - ./public:/usr/src/app/public
  test:
    build:
      context: .
      dockerfile: ./test/Dockerfile


networks:
  default:
    external:
      name: webplatform_suilabs