version: '3'
services:
  server:
    build: .
    container_name: tarbean
    environment:
      - VIRTUAL_HOST=tarbean.suilabs.com,static.suilabs.com
      - LETSENCRYPT_HOST=tarbean.suilabs.com,static.suilabs.com
      - LETSENCRYPT_EMAIL=borja.arias.upc@gmail.com
      - S3_ACCESS_KEY=${LC_S3_ACCESS_KEY}
      - S3_SECRET_KEY=${LC_S3_SECRET_KEY}
    volumes:
      - ./public:/usr/src/app/public

networks:
  default:
    external:
      name: webplatform_suilabs
